"""add_trends_and_scripts_tables

Revision ID: 330f7045cc51
Revises: 23456def7890
Create Date: 2026-03-02 09:59:52.188885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = '330f7045cc51'
down_revision: Union[str, None] = '23456def7890'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('keyword', sa.String(length=255), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('trend_score', sa.Float(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('video_count', sa.Integer(), nullable=True),
    sa.Column('growth_rate', sa.Float(), nullable=True),
    sa.Column('ai_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('suggested_tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('related_keywords', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('region', sa.String(length=10), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_keyword_source', 'trends', ['keyword', 'source'], unique=False)
    op.create_index('idx_source_category', 'trends', ['source', 'category'], unique=False)
    op.create_index('idx_trend_score_created', 'trends', ['trend_score', 'created_at'], unique=False)
    op.create_index(op.f('ix_trends_category'), 'trends', ['category'], unique=False)
    op.create_index(op.f('ix_trends_created_at'), 'trends', ['created_at'], unique=False)
    op.create_index(op.f('ix_trends_id'), 'trends', ['id'], unique=False)
    op.create_index(op.f('ix_trends_keyword'), 'trends', ['keyword'], unique=False)
    op.create_index(op.f('ix_trends_source'), 'trends', ['source'], unique=False)
    op.create_table('scripts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('trend_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('hook', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('cta', sa.Text(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=1536), nullable=True),
    sa.Column('ai_model', sa.String(length=50), nullable=True),
    sa.Column('generation_prompt', sa.Text(), nullable=True),
    sa.Column('generation_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('viral_potential', sa.Float(), nullable=True),
    sa.Column('readability_score', sa.Float(), nullable=True),
    sa.Column('used_count', sa.Integer(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('target_platforms', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('target_audience', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['trend_id'], ['trends.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_quality_viral', 'scripts', ['quality_score', 'viral_potential'], unique=False)
    op.create_index('idx_script_embedding', 'scripts', ['embedding'], unique=False, postgresql_using='ivfflat')
    op.create_index('idx_user_created', 'scripts', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_scripts_created_at'), 'scripts', ['created_at'], unique=False)
    op.create_index(op.f('ix_scripts_id'), 'scripts', ['id'], unique=False)
    op.create_index(op.f('ix_scripts_is_archived'), 'scripts', ['is_archived'], unique=False)
    op.create_index(op.f('ix_scripts_language'), 'scripts', ['language'], unique=False)
    op.create_index(op.f('ix_scripts_trend_id'), 'scripts', ['trend_id'], unique=False)
    op.create_index(op.f('ix_scripts_user_id'), 'scripts', ['user_id'], unique=False)
    op.alter_column('upload_quotas', 'last_daily_reset',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('upload_quotas', 'last_weekly_reset',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('upload_quotas', 'last_monthly_reset',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('upload_quotas', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('upload_quotas', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_upload_quotas_id'), 'upload_quotas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_upload_quotas_id'), table_name='upload_quotas')
    op.alter_column('upload_quotas', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('upload_quotas', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('upload_quotas', 'last_monthly_reset',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('upload_quotas', 'last_weekly_reset',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('upload_quotas', 'last_daily_reset',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_scripts_user_id'), table_name='scripts')
    op.drop_index(op.f('ix_scripts_trend_id'), table_name='scripts')
    op.drop_index(op.f('ix_scripts_language'), table_name='scripts')
    op.drop_index(op.f('ix_scripts_is_archived'), table_name='scripts')
    op.drop_index(op.f('ix_scripts_id'), table_name='scripts')
    op.drop_index(op.f('ix_scripts_created_at'), table_name='scripts')
    op.drop_index('idx_user_created', table_name='scripts')
    op.drop_index('idx_script_embedding', table_name='scripts', postgresql_using='ivfflat')
    op.drop_index('idx_quality_viral', table_name='scripts')
    op.drop_table('scripts')
    op.drop_index(op.f('ix_trends_source'), table_name='trends')
    op.drop_index(op.f('ix_trends_keyword'), table_name='trends')
    op.drop_index(op.f('ix_trends_id'), table_name='trends')
    op.drop_index(op.f('ix_trends_created_at'), table_name='trends')
    op.drop_index(op.f('ix_trends_category'), table_name='trends')
    op.drop_index('idx_trend_score_created', table_name='trends')
    op.drop_index('idx_source_category', table_name='trends')
    op.drop_index('idx_keyword_source', table_name='trends')
    op.drop_table('trends')
    # ### end Alembic commands ###
